# Generated by Django 4.1.3 on 2022-11-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(
                blank=True, db_index=True, default=0, null=True, verbose_name="Likes"
            ),
        ),
    ]
