# Generated by Django 4.1.3 on 2022-11-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_post_likes"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="name",),
        migrations.RemoveField(model_name="post", name="username",),
    ]
