# Generated by Django 4.1.3 on 2022-11-15 04:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_photo_remove_post_image"),
    ]

    operations = [
        migrations.DeleteModel(name="Photo",),
        migrations.AddField(
            model_name="post",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, db_index=True, max_length=255, verbose_name="image"
            ),
        ),
    ]
